In [1]:
import pandas as pd
import csv
import os

In [2]:
df = pd.read_csv("Valid_text.csv")
df

,3CE74519F0529BC236F00A672E84508C3F540E550072F31165C7B3CEBB60F68D,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,1
0,3E3CDEF43BF5DC97FAE44DB59892EDBB47248DEFEA66F6...,NaN,NaN,NaN,NaN,1
1,4FE4DA01C7F484F8080F5015E54A94D0DFBB90FD94CCB9...,NaN,NaN,NaN,NaN,1
2,0F51818899E3204550427F15929F6F1137392F28E02554...,NaN,NaN,NaN,NaN,1
3,3E1B9C71AD70E466FAFF2925BE34A384A5F0BD7119311B...,NaN,NaN,NaN,NaN,1
4,5CB50FB966D7145EF686D8ADBEA1E3B17F7EA798E92B85...,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...
158,3C432326F76648539DF6AB53D32F9498E3E7BC37C322EF...,NaN,NaN,NaN,NaN,1
159,5D6ABF300D8221DA69F094C66F901E8DC99C0C9BF4D2EC...,NaN,NaN,NaN,NaN,1
160,2FAE27F2A766268F89144AEE51795BBD563686B44E1CBB...,NaN,NaN,NaN,NaN,1
161,0F2883A17A4EE1BD8E3A8CCA7C587ECD92082501589981...,NaN,NaN,NaN,NaN,1
162,2F261633CED131A1468445F12B4498DF82B6B0A4893962...,NaN,NaN,NaN,NaN,1

In [26]:
dir_path = '/home/user/Downloads/AttackMalconv2/TrainingData/TestMalware/'
file_list=os.listdir(dir_path)
csv_file_name = '/home/user/Downloads/AttackMalconv2/TrainingData/new_file.csv'
max_size = 0.5*1024*1024
malware_files = []

for root, dirs, files in os.walk(dir_path):
    for file in files:
        file_path = os.path.join(root, file)
        file_size = os.path.getsize(file_path)
        if file_size < max_size:
            malware_files.append(file)

In [27]:
with open(csv_file_name, 'w', newline='') as csvfile:
    csv_write=csv.writer(csvfile)
    for filess in malware_files:
        csv_write.writerow([filess])